data: 
  data: grid
  dir: './data'
  batch_size: 8
  test_split: 0.2
  max_node_num: 361
  max_feat_num: 5
  init: deg

sde:
  x: 
    type: VP
    beta_min: 0.1
    beta_max: 1.0
    num_scales: 1000
  adj: 
    type: VP
    beta_min: 0.2
    beta_max: 0.8
    num_scales: 1000

model:
  x: ScoreNetworkX
  adj: ScoreNetworkA
  conv: GCN
  num_heads: 4
  depth: 5
  adim: 32
  nhid: 32
  num_layers: 7
  num_linears: 2
  c_init: 2
  c_hid: 8
  c_final: 4

train:
  name: test
  num_epochs: 5000
  save_interval: 2500
  print_interval: 1000
  reduce_mean: False
  lr: 0.01
  lr_schedule: True
  ema: 0.999
  weight_decay: 0.0001
  grad_norm: 1.0
  lr_decay: 0.999
  eps: 1.0e-5

sampler:
  predictor: Reverse
  corrector: Langevin
  snr: 0.1
  scale_eps: 0.7
  n_steps: 1

sample:
  use_ema: True
  noise_removal: True
  probability_flow: False
  eps: 1.0e-4
  seed: 13
